version: '3'

services:
   web1:
     image: medineshkatwal/myapp:v1
     container_name: v1
     ports:
      - "8081:3000"
   web2:
     image: medineshkatwal/myapp:v2
     container_name: v2
     ports:
      - "8082:3000"
   haproxy:
      image: million12/haproxy
      container_name: loadbalancer
      cap_add:
        - NET_ADMIN
      volumes:
        - ./haproxy.cfg:/etc/haproxy/haproxy.cfg
      ports:
        - "80:80"
