version: '3.1'

services:
    cowsay:
      image: swarmgs/cowsayhealth
      ports:
        - "7001:80"
      deploy:
        replicas: 1
        placement:
           constraints:
             - node.role==manager
