version: '3.1'

services:
   cowsay:
     image: swarmgs/cowsay
     ports: 
       - "7000:80"
     deploy:
       replicas: 1
       placement:
          constraints:
              - node.role==manager
