version: '3.1'

services:
    myapp:
      image: medineshkatwal/myapp:v2
      ports:
        - "3000:3000"
      deploy:
        replicas: 2
      healthcheck:
        test: curl -f -s -S localhost:3000/health
        interval: 2s
        timeout: 10s
        retries: 3